export const dataList = [
    {
        id: 1,
        title: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 2,
        title: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 3,
        title: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
      {
        id: 4,
        title: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 5,
        title: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 6,
        title: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
      {
        id: 7,
        title: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 8,
        title: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 9,
        title: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
      {
        id: 10,
        title: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 11,
        title: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 12,
        title: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
]