export const dataList = [
    {
        id: 1,
        NameClinic: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 2,
        NameClinic: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 3,
        NameClinic: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
      {
        id: 4,
        NameClinic: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 5,
        NameClinic: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 6,
        NameClinic: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
      {
        id: 7,
        NameClinic: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 8,
        NameClinic: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 9,
        NameClinic: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
      {
        id: 10,
        NameClinic: 'Andista Animal Care',
        serviceTime: '09.00 - 24.00 WIB',
        location: 'jakarta',
        address: 'Jl. Kamboja No.2C, Jakarta Barat',
        coverSrc: '/images/klinik1.png',
    },
    {
        id: 11,
        NameClinic: 'Mascota Pet Care',
        serviceTime: '09.00 - 20.00 WIB',
        location: 'malang',
        address: 'Jl. Kav. Perkebunan Raya, Bekasi',
        coverSrc: '/images/klinik2.png',
      },
      {
        id: 12,
        NameClinic: 'Dialo Vet Animal Care',
        serviceTime: '08.00 - 17.00 WIB',
        location: 'surabaya',
        address: 'Jl. Raya Sukahati No. 12A, Bogor',
        coverSrc: '/images/klinik3.png',
      },
]

export const communityList = [
  {
      id: 1,
      title: 'Komunitas Pecinta Kucing Jakarta',
      location: 'jakarta',
      established: 'Berdiri sejak 4 Maret 2016',
      coverSrc: '/images/komunitas1.png',
  },
  {
      id: 2,
      title: 'Komunitas Anjing Pemburu Indonesia',
      location: 'malang',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas2.png',
    },
    {
      id: 3,
      title: 'Komunitas Hamster Jawa Timur',
      location: 'surabaya',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas3.png',
    },
    {
      id: 4,
      title: 'Komunitas Pecinta Kucing Jakarta',
      location: 'jakarta',
      established: 'Berdiri sejak 4 Maret 2016',
      coverSrc: '/images/komunitas1.png',
  },
  {
      id: 5,
      title: 'Komunitas Anjing Pemburu Indonesia',
      location: 'malang',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas2.png',
    },
    {
      id: 6,
      title: 'Komunitas Hamster Malang',
      location: 'surabaya',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas3.png',
    },
    {
      id: 7,
      title: 'Komunitas Pecinta Kucing Jakarta',
      location: 'jakarta',
      established: 'Berdiri sejak 4 Maret 2016',
      coverSrc: '/images/komunitas1.png',
  },
  {
      id: 8,
      title: 'Komunitas Anjing Pemburu Indonesia',
      location: 'malang',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas2.png',
    },
    {
      id: 9,
      title: 'Komunitas Hamster Malang',
      location: 'surabaya',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas3.png',
    },
    {
      id: 10,
      title: 'Komunitas Pecinta Kucing Jakarta',
      location: 'jakarta',
      established: 'Berdiri sejak 4 Maret 2016',
      coverSrc: '/images/komunitas1.png',
  },
  {
      id: 11,
      title: 'Komunitas Anjing Pemburu Indonesia',
      location: 'malang',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas2.png',
    },
    {
      id: 12,
      title: 'Komunitas Hamster Malang',
      location: 'surabaya',
      established: 'Berdiri sejak 4 September 2020',
      coverSrc: '/images/komunitas3.png',
    },
]