export default [
    {
        id: 1,
        title: 'HaloPet Clinic',
        serviceTime: '9AM - 17.00PM',
        location: 'jakarta',
        rating: 5,
        price: 2500,
        coverSrc: '/images/clinic1.jpg',
    },
    {
        id: 2,
        title: 'Yosela Clinic',
        serviceTime: '7.00AM - 15.00PM',
        location: 'malang',
        rating: 4,
        price: 1000,
        coverSrc: '/images/clinic2.jpg',
      },
      {
        id: 3,
        title: 'DePet Clinic',
        serviceTime: '30-22min',
        deliveryFee: 4.94,
        location: 'surabaya',
        rating: 3,
        price: 2000,
        coverSrc: '/images/clinic3.jpg',
      },
      {
        id: 4,
        title: 'PetMate',
        serviceTime: '10-18min',
        deliveryFee: 2.14,
        location: 'medan',
        rating: 1,
        price: 1800,
        coverSrc: '/images/clinic4.jpg',
      },
      {
        id: 5,
        title: 'Hewania',
        serviceTime: '25-30min',
        deliveryFee: 6.79,
        location: 'bali',
        rating: 5,
        price: 2000,
        coverSrc: '/images/clinic5.jpg',
      },
]